name: docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-docs:
    name: terraform-docs-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Terraform documentation
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          output-file: ""
          output-method: ""
          template: ""
          git-push: "false"
          fail-on-diff: "true"