name: docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-docs:
    name: terraform-docs-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "false"
          fail-on-diff: "true"
